name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Run Check
        run: bun check:ci

  backend-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Run Lint
        run: uv run ruff check --output-format=github .

      - name: Run Format
        run: uv run ruff format . --check --diff
